### ISSUE TITLE
Passing Array Object Through URL 

### ISSUE THREAD

**Issue by syazie** [sorribas/phantom-render-stream#112] opened 2017-07-10 08:22 UTC
Is it possible to send array object through url? 

**app.js**
```
var username = "AAA";
var pets = [
   {id: 1, name: "cat"},
   {id: 2, name: "dog"},
   {id: 3, name: "sugar glider"}
];
var address = {
    line1: "Street A123",
    town: "Edinburgh",
    country: "Scotland"
};

render('http://localhost:8888/createForm.html?username='+username+
			'&pets='+pets+
			'&address='+address
	  	.pipe(fs.createWriteStream('customer.pdf'));
```

In 'createForm.html', I used AngularJS to read and write in the HTML.

**createForm.html**
```
 <script>
		var app = angular.module('myApp', []);

		app.config(function($locationProvider){
			$locationProvider.html5Mode(true);
		});

		app.controller('getDataCtrl', function($scope, $location) {
                         var url = decodeURIComponent( $location.url() );
			 var value = $location.search();
 
			$scope.username = value.username;
			$scope.pets = value.pets;
                       $scope.address = value.address;
            })
</script>

<body>
	  <div ng-app="onePayForm" ng-controller="getDataCtrl">
                   <p>{{username}}</p>
                  <p>{{pets[0].name}}</p>
                 <p>{{address.line1}}</p>
         </div>
</body>
```
After successfully create the 'customer.pdf'. The {{username}} successfully displayed in pdf but the pets and the address value not appear.

**Comment by markstos** [comment] 2017-07-10 14:56
This issue can be closed as being unrelated to this module. The problem is solved by the query string parsing module that your app uses, in combination with Angular. This module just passes the URL to render to the headless browser.

**Closed** 2017-07-11 02:17 UTC
